#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

my @templates = qw(
    /etc/cron.d/hotsync
    /etc/hotsync.conf
    /etc/rsyncd.conf
    /etc/rsyncd.secrets
    /etc/stunnel/stunnel.conf
    /etc/stunnel/stunnel.pem
);

#--------------------------------------------------
# actions for nethserver-hotsync-update event
#--------------------------------------------------
event_templates('nethserver-hotsync-update', @templates);
event_actions('nethserver-hotsync-update', qw(
    initialize-default-databases 00
));

#--------------------------------------------------
# actions for nethserver-hotsync-save event
#--------------------------------------------------
event_templates('nethserver-hotsync-save', @templates);
event_actions('nethserver-hotsync-save', qw(
    nethserver-hotsync-conf 70
    backup-config-execute 90
));
event_services('nethserver-hotsync-save', qw(
    stunnel restart
));

#--------------------------------------------------
# actions for certificate-update event
#--------------------------------------------------
event_templates('certificate-update', qw(
    /etc/stunnel/stunnel.pem
));