#!/bin/bash
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
# Install on spare server same packages installed on master

if [[ "$1" != "fixperm" ]]; then
    # Extract package file list
    /bin/tar -xf /var/lib/nethserver/backup/backup-config.tar.xz -C / var/lib/nethserver/backup/package-list --warning=no-timestamp

    # check internet connection before proceed with packages download
    echo -e "GET http://mirrorlist.nethserver.org HTTP/1.0\n\n" | nc mirrorlist.nethserver.org 80 > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        # launch reinstall action
        /etc/e-smith/events/actions/restore-config-reinstall

        if [[ $? != 0 ]]; then
            echo "[ERROR] restore-config-reinstall failed!" 1>&2
            ((++exit_code))
        fi
    else
        echo "[WARNING] Cannot download packages. Please check your internet connection."
    fi

    # load configuration backup on interface if its md5 is equal to its md5file
    backupfile="/var/lib/nethserver/backup/backup-config.tar.xz"
    md5file="${backupfile}.md5"
    md5sum ${backupfile} 2>/dev/null | grep -q $(cut -f 1 -d ' ' "${md5file}")
    if [[ $? == 0 ]]; then
        /etc/e-smith/events/actions/nethserver-backup-config-push2history || ((++exit_code))
    fi
fi

# fix permissions
if rpm -q --quiet nethserver-freepbx; then
  chown asterisk:asterisk /etc/freepbx.conf
  if [[ -e "/etc/freepbx_db.conf" ]]; then
    chown asterisk:asterisk /etc/freepbx_db.conf
  fi
  chown asterisk:asterisk /etc/amportal.conf
  chown -R asterisk:asterisk /etc/asterisk/
  chown -R asterisk:asterisk /var/lib/asterisk/
  chown -R asterisk:asterisk /var/www/html/freepbx/
fi

if rpm -q --quiet nethserver-mail-filter; then
  chown -R redis:redis /var/lib/redis/
  chown -R _rspamd:_rspamd /var/lib/rspamd/
fi

if rpm -q --quiet nethserver-ejabberd; then
  chown -R ejabberd:ejabberd /var/lib/nethserver/ejabberd/
fi

if rpm -q --quiet nethserver-openvpn; then
  chown -R srvmgr:adm /var/lib/nethserver/openvpn-tunnels/
fi

if rpm -q --quiet nethserver-mail-server; then
  chown -R vmail:vmail /var/lib/nethserver/vmail/
  chown root:vmail /var/lib/nethserver/sieve-scripts/
  COUNT=`/bin/ls -1 /var/lib/nethserver/sieve-scripts/*.svbin 2>/dev/null | /bin/wc -l`
  if [ $COUNT != 0 ]; then
    chown vmail:vmail /var/lib/nethserver/sieve-scripts/*.svbin
  fi
fi

if rpm -q --quiet nethserver-squidguard; then
  chown -R squid:squid /var/squidGuard/blacklists/
  chown -R ufdb:squid /var/squidGuard/blacklists/cache.execlists/
  chown -R ufdb:ufdb /var/ufdbguard/blacklists/
  chown -R ufdb:ufdb /var/ufdbguard/logs/
fi

if rpm -q --quiet nethserver-pulledpork; then
  chown -R suricata:suricata /etc/suricata/
fi

# avoid backup-data execution
if [[ -e /etc/cron.d/backup-data ]]; then
  /bin/rm /etc/cron.d/backup-data
fi

exit ${exit_code}
