#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# source configuration file
[ -f /etc/hotsync.conf ] && source /etc/hotsync.conf

if [[ $ROLE != 'slave' ]]; then
    echo "ERROR: Promotion to MASTER is possible only for SLAVE"
    exit 1
fi

# launch hotsync-slave to fix permissions before restore
/usr/sbin/hotsync-slave

# Enable NethServer events after yum
sed -i 's/enabled = 0/enabled = 1/g' /etc/yum/pluginconf.d/nethserver_events.conf

/sbin/e-smith/restore-config

if [[ $? == 0 ]]; then
    echo "[NOTICE] Configuration restore completed!"
else
    echo "[ERROR] restore-config failed. Last error messages from /var/log/messages:  "
    echo ""
    grep -E '(ERROR|FAIL)' /var/log/messages | tail -15 | sed 's/^/    /'
    echo ""
    ((++exit_code))
fi

# Check if network roles need to be assigned
flag=/var/run/.nethserver-fixnetwork
if [[ ! -f $flag ]]; then
    echo "To complete promotion to master, launch"
    echo ""
    echo "   /sbin/e-smith/signal-event post-restore-data"
    echo ""
else 
    echo "Go to Server Manager page \"Network\" and reassign roles to network interfaces"
    echo "and complete promotion to master by launching"
    echo ""
    echo "   /sbin/e-smith/signal-event post-restore-data"
    echo ""
    ((++exit_code))
fi

exit ${exit_code}
