#!/bin/bash
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
# Install on spare server same packages installed on master

# Extract package file list
/bin/tar -xf /var/lib/nethserver/backup/backup-config.tar.xz -C / var/lib/nethserver/backup/package-list --warning=no-timestamp

# launch reinstall action
/etc/e-smith/events/actions/restore-config-reinstall

if [[ $? != 0 ]]; then
    echo "[ERROR] restore-config-reinstall failed!" 1>&2
    ((++exit_code))
fi

# load configuration backup on interface if its md5 is equal to its md5file
backupfile="/var/lib/nethserver/backup/backup-config.tar.xz"
md5file="${backupfile}.md5"
md5sum ${backupfile} 2>/dev/null | grep -q $(cut -f 1 -d ' ' "${md5file}")
if [[ $? == 0 ]]; then
    /etc/e-smith/events/actions/nethserver-backup-config-push2history || ((++exit_code))
fi

exit ${exit_code}