#!/bin/sh

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# This script will restore mysql backup.
# The script mut be executed before /etc/.my.cnf is replaced by an expand-template

backup_dir=/var/lib/nethserver/backup/mysql/

if [ ! -f $backup_dir/mysql.dump ]; then
    exit 0
fi

if [[ x$(/sbin/e-smith/config getprop hotsync databases) == "xdisabled" ]] ; then 
    exit 0
fi

echo "Restoring mysql backup...";
/sbin/service mysqld status  >/dev/null
if [ $? -eq 0 ]; then
    /sbin/service mysqld stop >/dev/null
fi

# Restarting mysql without privileges
/usr/bin/mysqld_safe --skip-grant-tables&
/usr/bin/mysql -e 'show databases'&> /dev/null
while [ $? -ne 0 ]  # wait mysql to start
do
    sleep 1
    /usr/bin/mysql -e 'show databases'&> /dev/null
done


# drop mysql db if exists (backup restored after nethserver-mysql install)
/usr/bin/mysql -e "drop database mysql" 2>/dev/null
/usr/bin/mysql < $backup_dir/mysql.dump
if [ $? -ne 0 ]; then
    echo "Can't load mysql.dump backup"
    exit 1
fi

rm -f $backup_dir/mysql.dump

# restart mysqld as normal daemon
/sbin/service mysqld restart

# set new password accessing with the old one
/usr/bin/mysqladmin password `cat /etc/my.pwd`
if [ $? -ne 0 ]; then
    echo "Can't change root password"
    exit 1
fi

# update .my.cnf with new password
/sbin/e-smith/expand-template /root/.my.cnf

# update privileges tables (if needed)
/usr/bin/mysql_upgrade >/dev/null

# restore all dumps
for db in $(ls $backup_dir/*.dump 2> /dev/null)
do
    mv $db /etc/e-smith/sql/init/01_$(basename $db .dump).sql
done

exec /etc/e-smith/events/actions/nethserver-mysql-init
