#!/usr/bin/perl 
use strict;
use esmith::ConfigDB;

my $conf = esmith::ConfigDB->open || die("Could not open config db\n");
my $hotsync = $conf->get('hotsync') || die("there's no hotsync key\n");
my $role = $hotsync->prop('role')  || $role = "";
my $backup = $conf->get('backup-config');
my $BackupStatus = $backup->prop('status') || '';

if ($role eq 'spare') {
  #configuring spare
  #disable yum nethserver plugin
  system("sed","-i", 's/enabled = 1/enabled = 0/g',"/etc/yum/pluginconf.d/nethserver_events.conf");
  #disable backup config
  if ($BackupStatus eq 'enabled'){
    $backup->set_prop('status','disabled');
  }
} elsif ($role eq 'master') {
  #configuring master
  #enable yum nethserver plugin
  system("sed","-i", 's/enabled = 0/enabled = 1/g',"/etc/yum/pluginconf.d/nethserver_events.conf");
} else {
  #not configured as master or spare
  print ("Role not defined\n" );
  exit 0;
}

