#!/usr/bin/perl 
use strict;
use esmith::ConfigDB;

my $conf = esmith::ConfigDB->open || die("Could not open config db\n");
my $hotsync = $conf->get('hotsync');
my $role = $hotsync->prop('role')  || '';
my $backup = $conf->get('backup-config');
my $status = $backup->prop('status') || '';

if ($status eq 'enabled' && $role eq 'spare') {
    $backup->set_prop('status','disabled');
}

