#!/usr/bin/perl 

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;

my $conf = esmith::ConfigDB->open || die("Could not open config db\n");
my $hotsync = $conf->get('hotsync') || die("there's no hotsync key\n");
my $role = $hotsync->prop('role')  || "";
my $backup = $conf->get('backup-config');
my $BackupStatus = $backup->prop('status') || '';

if ($role eq 'spare') {
  #configuring spare
  #disable yum nethserver plugin
  system("sed","-i", 's/enabled = 1/enabled = 0/g',"/etc/yum/pluginconf.d/nethserver_events.conf");
  #disable backup config
  if ($BackupStatus eq 'enabled'){
    $backup->set_prop('status','disabled');
  }
} elsif ($role eq 'master' || $role eq 'server') {
  #configuring master
  #enable yum nethserver plugin
  system("sed","-i", 's/enabled = 0/enabled = 1/g',"/etc/yum/pluginconf.d/nethserver_events.conf");
} else {
  #not configured as master or spare
  print ("Role not defined\n" );
  exit 0;
}

